version: "3.7"
services:
  server:
    build: ./server/
    volumes:
      - ./server/:/usr/src/app
    ports:
      - "9090:9090"
    hostname: server
    environment:
      SECRET: ''
  # client:
  #   build: ./client/
  #   volumes:
  #     - ./client/:/usr/src/app
  #   ports:
  #     - "3000:3000"
  #   hostname: client
  #   depends_on:
  #     - server
